service: serverless-wedding


provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: eu-west-2

plugins:
  - serverless-offline

functions:
  api:
    handler: api/api.handler
    events:
      - http: ANY /
      - http: 'ANY /{param+}'
